### PR TITLE
fixed color bug team page

### LINKED ISSUE #9: Mobile issues on the Team page
I have found an issue while surfing the site with my smartphone. The team page seems broken, as you can see from the following video.

https://user-images.githubusercontent.com/14623986/160023200-ad416aff-745a-40b0-b80e-28aaa183ed99.MOV

I'll probably check the responsiveness of the site.

Model: iPhone XR
OS: iOS 15.3.1
Browser: Safari

### PR DESCRIPTION
**Pull request by 404answernotfound**
fixes #9

### CODE REVIEW

File: src/views/Team.vue [hunk 1]
```diff
@@ -204,11 +203,14 @@ $color_grey_dark: $nord2;
...
+    color: $color_white;
     .description {
       background: $nord2;
-      h2,
-      .read-more a {
+      color: #fff !important;
+      h1,
+      .p a {
         color: $nord4;
+        color: #fff;
```
Comment (TheJoin95) [inline src/views/Team.vue:213]: Se possiamo, usiamo le variabili sass come sopra

**Review by davideimola — APPROVED** [review]
LGTM it seems fixed. Good joob @404answernotfound 

image

**Review by Wabri — APPROVED** [review]
